#!/bin/env python3

import ed
import sys

st=None
if len(sys.argv) > 1:
    for arg in sys.argv[1:]:
        if arg == "-h":
            print(help)
            sys.exit(0)
        elif arg == "-r":
            # Reverse video
            st = "\033[7m"

ed.editor(st).edit()
